#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Do not share history between sessions
unsetopt SHARE_HISTORY

setopt nohup # and dont kill BG jobs when shell exits
setopt notify # notify of BG job completion immediately
setopt recexact # recognise exact, ambiguous matches
setopt completeinword          # not just at the end
setopt alwaystoend             # when complete from middle, move cursor
setopt promptcr # ensure a new line before prompt is drawn
setopt interactivecomments # escape commands so i can use them later

# =========================== Local changes ==================================

# Load aliases
if [[ -s "$HOME/.aliases" ]]; then
    . "$HOME/.aliases"
fi

# load bash/zsh functions
if [[ -s "$HOME/.functions" ]]; then
    . "$HOME/.functions"
fi

# import hhigliht function from paoloantiori
# https://github.com/paoloantinori/hhighlighter
source "$HOME/.h.sh"

# Ruby ENV completion
eval "$(rbenv init -)"
